tasks:
  - name: Dev Server
    init: npm install
    command: npm run dev

  - name: Lesson Context
    command: |
      gp ports await 3000
      gp open src/lessons/${lesson}/index.astro
      gp preview $(gp url 3000)/${lesson}
      exit
    openMode: split-right

vscode:
  extensions:
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
