tasks:
  init: npm install
  command: |
    npm run dev
    gp ports await 3000
    gp open src/lessons/${lesson}/index.astro
    gp preview $(gp url 3000)/${lesson}
vscode:
  extensions:
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
